/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ellinor
 */
public class MinaSidor extends javax.swing.JFrame {

    private String inloggadPerson;
    private PreparedStatement pst;
    private ResultSet rs;
    private Connection con;
     
   public MinaSidor(String anvandarnamn) {
        initComponents();
        lblBekräftelse.setVisible(false);
        inloggadPerson = anvandarnamn;
        pst= null;
        rs=null;
        con= null;
        lblÄndraLösen.setText("Ändra Lösenord för" + " " + inloggadPerson);
    }


 
    public void bytLösen()  {  if(Validate.inteTomt(pwÄndraLösen)){
        try {
        String lösen = pwÄndraLösen.getText();
        String ändraLösen = "UPDATE `user` SET `losenord`=? WHERE `anamn`=?";
        con = DriverManager.getConnection("jdbc:mysql://mysqlse.fragnet.net:3306/111653_clientdb", "111653" ,"81374364");
        pst=con.prepareStatement(ändraLösen);
        pst.setString(1, lösen);
        pst.setString(2, inloggadPerson);
        pst.executeUpdate();
        lblBekräftelse.setText("Lösenordet har uppdaterats till" + " " + pwÄndraLösen.getText());
        lblBekräftelse.setVisible(true);
        } catch (Exception e) {
            System.out.println("Intern felmeddelande, Hittar inte Admin-Status: " + e.getMessage());
        }
    }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblÄndraLösen = new javax.swing.JLabel();
        lblNyttLösen = new javax.swing.JLabel();
        pwÄndraLösen = new javax.swing.JPasswordField();
        lblBekräftelse = new javax.swing.JLabel();
        btnÄndraLösen = new javax.swing.JButton();
        btnMöte = new javax.swing.JButton();
        btnStartsida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblÄndraLösen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblÄndraLösen.setText("Ändra lösenord");

        lblNyttLösen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNyttLösen.setText("Nytt lösenord:");

        pwÄndraLösen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwÄndraLösen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwÄndraLösenActionPerformed(evt);
            }
        });

        lblBekräftelse.setForeground(new java.awt.Color(0, 204, 0));
        lblBekräftelse.setText("Bekräftelse");

        btnÄndraLösen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnÄndraLösen.setText("Ändra lösenord");
        btnÄndraLösen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraLösenActionPerformed(evt);
            }
        });

        btnMöte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMöte.setText("Mötesförfrågningar");

        btnStartsida.setText("Startsida");
        btnStartsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartsidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnStartsida, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMöte, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblÄndraLösen)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnÄndraLösen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBekräftelse, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNyttLösen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwÄndraLösen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartsida)
                .addGap(50, 50, 50)
                .addComponent(btnMöte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblÄndraLösen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNyttLösen)
                    .addComponent(pwÄndraLösen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnÄndraLösen)
                    .addComponent(lblBekräftelse))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwÄndraLösenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwÄndraLösenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwÄndraLösenActionPerformed

    private void btnÄndraLösenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraLösenActionPerformed
        bytLösen();
    }//GEN-LAST:event_btnÄndraLösenActionPerformed

    private void btnStartsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartsidaActionPerformed
                   String anvandarnamn = "";
                   Startsida start = new Startsida(anvandarnamn);
                   start.setVisible(true);
                   MinaSidor.this.dispose();
    }//GEN-LAST:event_btnStartsidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String anvandarnamn = "";
                new MinaSidor(anvandarnamn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMöte;
    private javax.swing.JButton btnStartsida;
    private javax.swing.JButton btnÄndraLösen;
    private javax.swing.JLabel lblBekräftelse;
    private javax.swing.JLabel lblNyttLösen;
    private javax.swing.JLabel lblÄndraLösen;
    private javax.swing.JPasswordField pwÄndraLösen;
    // End of variables declaration//GEN-END:variables
}
