
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebbe
 */
public class SeBesvaradeMötesförfrågningar extends javax.swing.JFrame {
    public String inloggadPerson;
    Connection con = null;  
    private String möteVärde;
    private String möteTid;
    private String möteID;
    /**
     * Creates new form SeBesvaradeMötesförfrågningar
     */
    public SeBesvaradeMötesförfrågningar(String anvandarnamn) {
        inloggadPerson = anvandarnamn;
        initComponents();
        DisplayTable();
    }
    
    private void DisplayTable(){
    
        try
        {
           con = DriverManager.getConnection("jdbc:mysql://mysqlse.fragnet.net:3306/111653_clientdb", "111653" ,"81374364");
           String sql = "select `användarnamn`, `möte`, `möteID` from `user_skapat_möte` where `användarnamn`=?";
           PreparedStatement pstmt = con.prepareStatement(sql);
           pstmt.setString(1, inloggadPerson);
           ResultSet rs = pstmt.executeQuery();
           tblMöten.setModel(DbUtils.resultSetToTableModel(rs));
           
       }
       
       catch (Exception ex){
       
       }
   }
    
    public void hämtaMöteVärde(){
    int rad = tblMöten.getSelectedRow();                                   //Visar markrad rad i tabellen
    möteVärde = tblMöten.getModel().getValueAt(rad, 2).toString();
    }
    
    public void hämtaBästaTidochID(){
    int rad=tblTider.getSelectedRow();
    möteTid = tblTider.getModel().getValueAt(rad, 1).toString();
    möteID = tblTider.getModel().getValueAt(rad, 0).toString();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblÖnskadeTider = new javax.swing.JLabel();
        btnMinaSidor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMöten = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTider = new javax.swing.JTable();
        lblDinaMöten = new javax.swing.JLabel();
        btnSkapaMöte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblÖnskadeTider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblÖnskadeTider.setText("Önskade tider");

        btnMinaSidor.setText("Mina sidor");
        btnMinaSidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaSidorActionPerformed(evt);
            }
        });

        tblMöten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "titel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMöten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMötenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMöten);
        tblMöten.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblTider.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "titel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTider);
        tblTider.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblDinaMöten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDinaMöten.setText("Dina möten");

        btnSkapaMöte.setText("Skapa möte med vald tid");
        btnSkapaMöte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaMöteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinaSidor)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblDinaMöten)
                        .addGap(285, 285, 285)
                        .addComponent(lblÖnskadeTider)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSkapaMöte)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblÖnskadeTider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDinaMöten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSkapaMöte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(btnMinaSidor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaSidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaSidorActionPerformed
        try {
            String anvandarnamn = inloggadPerson;
            MinaSidor start = new MinaSidor(anvandarnamn);
            start.setVisible(true);
            SeBesvaradeMötesförfrågningar.this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Mötesförfrågning.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMinaSidorActionPerformed

    private void tblMötenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMötenMouseClicked
        hämtaMöteVärde();
        try{
        con = DriverManager.getConnection("jdbc:mysql://mysqlse.fragnet.net:3306/111653_clientdb", "111653" ,"81374364");
        String sql = "select `möte_fk`, `bäst_tid` from `user_möte` where `möte_fk`=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, möteVärde);
        ResultSet rs = pst.executeQuery();
        tblTider.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tblMötenMouseClicked

    private void tblTiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiderMouseClicked

    }//GEN-LAST:event_tblTiderMouseClicked

    private void btnSkapaMöteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaMöteActionPerformed
        hämtaBästaTidochID();
        try{
        con = DriverManager.getConnection("jdbc:mysql://mysqlse.fragnet.net:3306/111653_clientdb", "111653" ,"81374364");
        String sql = "Update `möte` set `datum`=? where `ID`=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, möteTid);
        pst.setString(2, möteID);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Mötet är bokat", "Bekräftelse", JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e){
        System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSkapaMöteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeBesvaradeMötesförfrågningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeBesvaradeMötesförfrågningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeBesvaradeMötesförfrågningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeBesvaradeMötesförfrågningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String anvandarnamn="";
                new SeBesvaradeMötesförfrågningar(anvandarnamn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinaSidor;
    private javax.swing.JButton btnSkapaMöte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDinaMöten;
    private javax.swing.JLabel lblÖnskadeTider;
    private javax.swing.JTable tblMöten;
    private javax.swing.JTable tblTider;
    // End of variables declaration//GEN-END:variables
}
